version: '3.9'
services:
  sleekdxbapi:
    container_name: sleekdxb-api
    image: sleekdxb/api:1.0.1
    build: . 
    ports:
      - 4444:4444
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:12
    container_name: db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: sleekdxb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - sxdb_data:/var/lib/postgresql/data

volumes:
  sxdb_data: {}
